Fix and improve `get_model`, `get_base_model`, `get_tuned_model`
google-gemini/generative-ai-python pull request #339
Opened 2024-05-14 18:04 UTC by Faisal-Alsrheed

This PR introduces several refinements to the model fetching functions `get_model`, `get_base_model`, `get_tuned_model`

The changes aim to improve clarity, enforce strict naming conventions, and reduce redundancy in the codebase.

2024-05-16 16:43 UTC, Faisal-Alsrheed commented
Hi @MarkDaoust :)

Let me know if you would like me to split this into multiple PRs.

2024-05-17 01:03 UTC, MarkDaoust submitted a review, later dismissed
This is great. Thank you!

2024-05-17 01:12 UTC, MarkDaoust approved these changes

2024-05-17 01:19 UTC, MarkDaoust requested changes
Wait I need to look at that TODO before merging this.

2024-05-17 03:43 UTC, mayureshagashe2105 commented
> Wait I need to look at that TODO before merging this.

The one in the permission_types? I should submit it in a separate PR.

@Faisal-Alsrheed thank you for the typos and other fixes :)

2024-05-17 18:09 UTC, MarkDaoust commented on CONTRIBUTING.md
> +python -m unittest discover -s /workspaces/generative-ai-python/tests
```suggestion
python -m unittest discover -s tests
```

2024-05-17 18:09 UTC, MarkDaoust commented on CONTRIBUTING.md
>  ```
```suggestion
# or more simply
python -m unittest
```
```

2024-05-17 18:30 UTC, MarkDaoust requested changes

2024-05-17 18:30 UTC, MarkDaoust commented on CONTRIBUTING.md
> +pytest /workspaces/generative-ai-python/tests
```suggestion
pytest tests

# or more simply
pytest
```

2024-05-17 18:30 UTC, MarkDaoust approved these changes

2024-05-17 18:32 UTC, MarkDaoust commented
> The one in the permission_types? I should submit it in a separate PR.

No I meant the one at the end of the PR description.

I think this is good to submit.

2024-05-17 18:52 UTC, merged